public enum UIEvents {
    InfoTextUpdate,
    UpdateCursor,
    GrabbedAbilityCard,
    ReleasedAbilityCard,
    AddBattleInformation,
    ShowUnitHighlight,
    HideUnitHighlight,
    GiveCard,
    ShowEnemyCardHand,
    HideEnemyCardHand,
    PopUpWindow,
    ShowPauseMenu,
    DoFade,
}